/* 🤖 this file was generated by svg-to-ts */
export const icons: { [key in MyIconType]: string } = {
	add: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none"><path fill="#000" fill-rule="evenodd" d="M7.345 4.017a42.252 42.252 0 0 1 9.31 0c1.713.192 3.095 1.541 3.296 3.26a40.66 40.66 0 0 1 0 9.446c-.201 1.719-1.583 3.068-3.296 3.26-3.069.343-6.241.343-9.31 0-1.713-.192-3.095-1.541-3.296-3.26a40.653 40.653 0 0 1 0-9.445c.201-1.72 1.583-3.07 3.295-3.26ZM12 7.007a.75.75 0 0 1 .75.75v3.493h3.493a.75.75 0 0 1 0 1.5H12.75v3.493a.75.75 0 1 1-1.5 0V12.75H7.757a.75.75 0 0 1 0-1.5h3.493V7.757a.75.75 0 0 1 .75-.75Z" clip-rule="evenodd"/></svg>',
};
export type MyIconType = 'add';
